export type ErrorSeverity = "low" | "medium" | "high" | "critical";
export type ErrorDefinition = { code: string; name: string; service: string; severity: ErrorSeverity; description: string };

export const ERROR_CATALOG: ErrorDefinition[] = [
  { code: "AI-001", name: "AI 分析錯誤", service: "analysis", severity: "high", description: "分析服務未能完成目前請求，可能與模型回應、格式解析或上游服務異常有關。" },
  { code: "AI-002", name: "AI 回應逾時", service: "analysis", severity: "medium", description: "AI 在允許時間內沒有完成回應，請稍後重新嘗試。" },
  { code: "AI-003", name: "AI 回應格式無法解析", service: "analysis", severity: "medium", description: "分析服務回傳的內容不符合系統需要的資料格式。" },
  { code: "AI-004", name: "AI 提示內容不完整", service: "analysis", severity: "low", description: "目前輸入缺少完成分析所需的資訊。" },
  { code: "AI-005", name: "AI 模型暫時不可用", service: "analysis", severity: "high", description: "目前沒有可用的 AI 模型可以處理請求。" },
  { code: "AI-006", name: "AI 額度已使用完畢", service: "analysis", severity: "medium", description: "本帳號或平台的 AI 使用額度已達上限，請等待額度重置或聯絡管理員。" },
  { code: "AI-007", name: "AI 請求內容過長", service: "analysis", severity: "low", description: "輸入內容超過目前模型能處理的長度。" },
  { code: "AI-008", name: "AI 供應商連線失敗", service: "analysis", severity: "high", description: "系統無法連接 AI 供應商或供應商拒絕請求。" },
  { code: "AI-009", name: "AI 安全檢查未通過", service: "analysis", severity: "high", description: "請求內容觸發安全性限制，因此沒有執行分析。" },
  { code: "AI-010", name: "AI 服務暫時忙碌", service: "analysis", severity: "medium", description: "目前同時使用分析服務的人數較多，請稍後再試。" },
  { code: "AI-011", name: "AI 額度資料同步失敗", service: "analysis", severity: "high", description: "分析額度狀態無法正確讀取，為避免錯誤扣除，系統已暫停此次分析。" },
  { code: "AUTH-001", name: "登入狀態已失效", service: "auth", severity: "medium", description: "登入工作階段已過期，請重新登入。" },
  { code: "AUTH-002", name: "沒有操作權限", service: "auth", severity: "high", description: "目前帳號沒有執行此操作所需的權限。" },
  { code: "AUTH-003", name: "管理員驗證失敗", service: "auth", severity: "high", description: "管理員入口驗證未通過，系統沒有執行任何管理操作。" },
  { code: "AUTH-004", name: "帳號被暫停", service: "auth", severity: "high", description: "帳號目前被停權或限制使用部分功能。" },
  { code: "DB-001", name: "資料庫連線失敗", service: "database", severity: "critical", description: "網站無法連接主要資料庫，可能影響登入、活動、商城與分析服務。" },
  { code: "DB-002", name: "資料讀取失敗", service: "database", severity: "high", description: "系統讀取資料時發生異常，請稍後再試。" },
  { code: "DB-003", name: "資料寫入失敗", service: "database", severity: "high", description: "系統沒有成功保存此次操作，請不要重複付款或重複送出。" },
  { code: "DB-004", name: "資料格式不一致", service: "database", severity: "high", description: "資料庫結構與目前網站版本不一致，需要管理員檢查 migration。" },
  { code: "NET-001", name: "網路連線中斷", service: "site", severity: "medium", description: "瀏覽器與網站之間的連線中斷。" },
  { code: "NET-002", name: "請求逾時", service: "site", severity: "medium", description: "伺服器在允許時間內沒有完成請求。" },
  { code: "NET-003", name: "服務回應異常", service: "site", severity: "high", description: "服務回傳無法辨識的錯誤狀態。" },
  { code: "SHOP-001", name: "J 幣餘額不足", service: "shop", severity: "low", description: "目前餘額不足以購買這件商品。" },
  { code: "SHOP-002", name: "商品已售罄", service: "shop", severity: "low", description: "商品庫存已用完。" },
  { code: "SHOP-003", name: "商品已經擁有", service: "shop", severity: "low", description: "帳號已經擁有這件商品，不能重複購買。" },
  { code: "SHOP-004", name: "商城交易失敗", service: "shop", severity: "high", description: "商城交易沒有完成，請檢查交易紀錄與 J 幣餘額。" },
  { code: "SHOP-005", name: "頭像框尚未擁有", service: "shop", severity: "low", description: "只能套用已購買、已獲得或已合法解鎖的頭像框。" },
  { code: "UPLOAD-001", name: "檔案上傳失敗", service: "upload", severity: "medium", description: "檔案沒有成功上傳，請檢查檔案大小與網路連線。" },
  { code: "UPLOAD-002", name: "檔案格式不支援", service: "upload", severity: "low", description: "目前不支援此檔案格式。" },
  { code: "UPLOAD-003", name: "檔案超過大小限制", service: "upload", severity: "low", description: "檔案超過網站允許的大小。" },
  { code: "EVENT-001", name: "活動載入失敗", service: "events", severity: "medium", description: "活動資料沒有成功載入。" },
  { code: "EVENT-002", name: "活動報名失敗", service: "events", severity: "high", description: "活動報名沒有成功完成，請檢查名額與報名狀態。" },
  { code: "EVENT-003", name: "揪團建立失敗", service: "events", severity: "medium", description: "揪團資料沒有成功保存。" },
  { code: "MAIL-001", name: "錯誤通知寄送失敗", service: "mail", severity: "high", description: "網站已記錄錯誤，但無法透過 SMTP 寄送通知。" },
  { code: "MAIL-002", name: "回報信箱設定缺失", service: "mail", severity: "high", description: "伺服器尚未設定 SMTP 必要環境變數。" },
  { code: "PWA-001", name: "離線快取版本不一致", service: "site", severity: "low", description: "瀏覽器快取的網站版本與目前版本不同，請重新載入。" },
  { code: "SYS-001", name: "服務維護中", service: "site", severity: "critical", description: "管理員已暫停此服務，以避免資料損壞或錯誤擴大。" },
  { code: "SYS-002", name: "未知系統錯誤", service: "site", severity: "high", description: "發生尚未分類的系統異常，請回報錯誤代碼與發生頁面。" },
];

export function getErrorDefinition(code?: string | null) { return ERROR_CATALOG.find((item) => item.code === code) ?? null; }
