import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, ArrowRight, ShieldAlert } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { ERROR_CATALOG } from "@/lib/error-codes";

const severityLabel: Record<string, string> = { low: "低影響", medium: "中影響", high: "高影響", critical: "嚴重" };

export default async function ErrorCodesPage() {
  try { await requireAdmin(); } catch { redirect("/"); }
  return <div className="mx-auto max-w-5xl px-4 py-8 md:px-8"><div className="mb-8"><p className="text-xs font-black tracking-[0.24em] text-brand-600">ADMIN ERROR DIRECTORY</p><h1 className="mt-2 font-display text-3xl font-black text-main">錯誤代碼與處理說明</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-soft">此頁面只供管理員查看完整錯誤代碼目錄。一般使用者只會看到自己遇到的錯誤代碼與對應回報入口。</p></div><div className="mb-6 flex items-start gap-3 rounded-3xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-100"><ShieldAlert className="mt-0.5 shrink-0 text-amber-500" size={20} /><p>高影響或嚴重錯誤可能觸發服務保護。完整代碼與內部處理說明不可公開分享。</p></div><div className="space-y-3">{ERROR_CATALOG.map((item) => <article id={item.code} key={item.code} className="card-surface rounded-3xl p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><code className="rounded-lg bg-brand-500/10 px-2.5 py-1 text-sm font-black text-brand-700 dark:text-brand-300">{item.code}</code><span className="font-display text-lg font-black text-main">{item.name}</span></div><p className="mt-2 text-sm leading-6 text-soft">{item.description}</p></div><span className={`flex shrink-0 items-center gap-1 rounded-full px-3 py-1.5 text-xs font-black ${item.severity === "critical" ? "bg-rose-500 text-white" : item.severity === "high" ? "bg-orange-100 text-orange-700" : item.severity === "medium" ? "bg-amber-100 text-amber-700" : "bg-brand-100 text-brand-700"}`}><AlertTriangle size={13} />{severityLabel[item.severity]}</span></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--color-border)] pt-3 text-xs text-soft"><span>服務分類：<strong className="text-main">{item.service}</strong></span><Link href={`/support/report?kind=error&code=${item.code}`} className="inline-flex items-center gap-1 font-black text-brand-600 hover:underline">回報此錯誤 <ArrowRight size={14} /></Link></div></article>)}</div></div>;
}
