"use client";
import { useCallback, useEffect, useState } from "react";
import { SectionTitle, EmptyState, Badge } from "@/components/ui";
import { Loader2, Download, Printer, RefreshCw, Users, UserPlus, Eye, MousePointerClick, Activity, AlertTriangle } from "lucide-react";

type AnalyticsData = { range: { from: string; to: string }; summary: Record<string, number>; funnel: Record<string, number>; trends: Array<Record<string, string | number>>; topPages: Array<Record<string, string | number>>; topFeatures: Array<Record<string, string | number>>; sources: Array<Record<string, string | number>>; devices: Array<Record<string, string | number>>; errors: Array<Record<string, string | number>>; realtime: Record<string, string | number> };
const empty: AnalyticsData = { range: { from: "", to: "" }, summary: {}, funnel: {}, trends: [], topPages: [], topFeatures: [], sources: [], devices: [], errors: [], realtime: {} };
const funnelSteps = [{ key: "landing", label: "進入網站" }, { key: "register_page", label: "查看註冊頁" }, { key: "register_started", label: "開始註冊" }, { key: "register_submitted", label: "送出註冊" }, { key: "register_success", label: "完成註冊" }, { key: "email_verified", label: "Email 驗證" }, { key: "first_login", label: "首次登入" }];
function num(value: unknown) { return Number(value || 0); }
function pct(value: number, base: number) { return base ? `${Math.round(value / base * 100)}%` : "—"; }
function csvCell(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }

export default function AdminAnalyticsPage() {
  const today = new Date().toISOString().slice(0, 10);
  const weekDate = new Date(`${today}T00:00:00.000Z`);
  weekDate.setUTCDate(weekDate.getUTCDate() - 6);
  const week = weekDate.toISOString().slice(0, 10);
  const [from, setFrom] = useState(week);
  const [to, setTo] = useState(today);
  const [data, setData] = useState<AnalyticsData>(empty);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const res = await fetch(`/api/admin/analytics?from=${from}&to=${to}`, { cache: "no-store" }); const body = await res.json(); if (!res.ok) throw new Error(body.error || "分析資料載入失敗"); setData(body); } catch (err) { setError(err instanceof Error ? err.message : "分析資料載入失敗"); } finally { setLoading(false); } }, [from, to]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  function exportCsv() { const rows = [{ section: "summary", ...data.summary }, ...data.trends.map((row) => ({ section: "trend", ...row })), ...data.topPages.map((row) => ({ section: "top_page", ...row })), ...data.topFeatures.map((row) => ({ section: "top_feature", ...row })), ...data.sources.map((row) => ({ section: "source", ...row }))]; const keys = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))); const csv = [keys, ...rows.map((row) => keys.map((key) => row[key as keyof typeof row]))].map((row) => row.map(csvCell).join(",")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `joinjoy-analytics-${from}-${to}.csv`; a.click(); URL.revokeObjectURL(url); }
  const summary = data.summary; const funnel = data.funnel; const maxTrend = Math.max(1, ...data.trends.map((row) => num(row.visitors)));
  return <div className="analytics-print flex flex-col gap-6"><SectionTitle eyebrow="ADMIN / ANALYTICS" title="網站分析專區" action={<div className="flex gap-2 print:hidden"><button onClick={() => void load()} className="inline-flex items-center gap-1 rounded-full border border-[var(--color-border)] px-3 py-2 text-xs font-bold text-soft"><RefreshCw size={14} />重新整理</button><button onClick={exportCsv} className="inline-flex items-center gap-1 rounded-full border border-brand-200 px-3 py-2 text-xs font-bold text-brand-600"><Download size={14} />CSV</button><button onClick={() => window.print()} className="inline-flex items-center gap-1 rounded-full bg-brand-500 px-3 py-2 text-xs font-bold text-white"><Printer size={14} />匯出 PDF</button></div>} />
    <div className="card-surface flex flex-wrap items-center gap-3 rounded-2xl p-4 print:hidden"><label className="text-sm text-soft">開始日期 <input type="date" value={from} max={to} onChange={(e) => setFrom(e.target.value)} className="ml-2 rounded-xl border border-[var(--color-border)] bg-app px-3 py-2 text-sm text-main" /></label><label className="text-sm text-soft">結束日期 <input type="date" value={to} min={from} max={today} onChange={(e) => setTo(e.target.value)} className="ml-2 rounded-xl border border-[var(--color-border)] bg-app px-3 py-2 text-sm text-main" /></label><span className="text-xs text-soft">資料來源：實際 analytics events，匿名 visitor ID 不含直接識別資料</span></div>
    {loading ? <div className="flex justify-center py-16"><Loader2 className="animate-spin text-brand-500" /></div> : error ? <div className="rounded-2xl bg-rose-50 p-5 text-sm text-rose-600">{error}</div> : <>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={<Users size={18} />} label="訪客數" value={num(summary.visitors)} /><Metric icon={<UserPlus size={18} />} label="新註冊" value={num(summary.registrations)} /><Metric icon={<Eye size={18} />} label="頁面瀏覽" value={num(summary.page_views)} /><Metric icon={<MousePointerClick size={18} />} label="事件數" value={num(summary.events)} /><Metric icon={<Activity size={18} />} label="活躍 session" value={num(data.realtime.active_sessions)} /></div>
      <section className="card-surface rounded-3xl p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-display text-xl font-black text-main">註冊漏斗</h2><p className="mt-1 text-sm text-soft">每一步以匿名 visitor 去重，避免同一使用者重複操作灌水。</p></div><Badge tone="coral">放棄 {Math.max(0, num(funnel.register_page) - num(funnel.register_success))} 人</Badge></div><div className="mt-6 grid gap-3 md:grid-cols-7">{funnelSteps.map((step, index) => { const count = num(funnel[step.key]); const previous = index ? num(funnel[funnelSteps[index - 1].key]) : count; return <div key={step.key} className="rounded-2xl bg-app-soft p-3"><p className="text-xs text-soft">{step.label}</p><p className="mt-2 text-2xl font-black text-main">{count.toLocaleString()}</p><p className="mt-1 text-xs font-bold text-brand-600">{index ? `${pct(count, previous)} 轉換` : "基準"}</p><p className="text-xs text-coral-600">{index ? `${Math.max(0, previous - count)} 人流失` : ""}</p></div>; })}</div></section>
      <div className="grid gap-6 lg:grid-cols-2"><section className="card-surface rounded-3xl p-5 sm:p-7"><h2 className="font-display text-xl font-black text-main">每日流量與註冊</h2><div className="mt-5 space-y-3">{data.trends.length ? data.trends.map((row) => <div key={String(row.day)}><div className="mb-1 flex justify-between text-xs"><span className="text-soft">{String(row.day).slice(0, 10)}</span><span className="font-bold text-main">{num(row.visitors)} 訪客 · {num(row.registrations)} 註冊</span></div><div className="h-2 overflow-hidden rounded-full bg-app-soft"><div className="h-full rounded-full bg-brand-500" style={{ width: `${Math.max(2, num(row.visitors) / maxTrend * 100)}%` }} /></div></div>) : <EmptyState title="此區間尚無趨勢資料" />}</div></section><section className="card-surface rounded-3xl p-5 sm:p-7"><h2 className="font-display text-xl font-black text-main">即時活動</h2><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="活躍 session" value={num(data.realtime.active_sessions)} compact /><Metric label="活躍訪客" value={num(data.realtime.active_visitors)} compact /><Metric label="近 15 分鐘事件" value={num(data.realtime.recent_events)} compact /></div><p className="mt-4 text-xs text-soft">以近 30 分鐘事件估算，避免為即時分析增加高頻資料庫負擔。</p></section></div>
      <div className="grid gap-6 lg:grid-cols-2"><Ranking title="熱門頁面" rows={data.topPages} nameKey="path" valueKey="views" secondKey="unique_views" secondLabel="unique" /><Ranking title="熱門功能與事件" rows={data.topFeatures} nameKey="name" valueKey="count" secondKey="unique_users" secondLabel="unique" /></div>
      <div className="grid gap-6 lg:grid-cols-3"><Ranking title="來源分析" rows={data.sources} nameKey="source" valueKey="visitors" secondKey="registrations" secondLabel="註冊" /><Ranking title="裝置分析" rows={data.devices} nameKey="device" valueKey="visitors" secondKey="events" secondLabel="事件" /><section className="card-surface rounded-3xl p-5"><h2 className="font-display text-lg font-black text-main"><AlertTriangle className="mr-1 inline text-coral-500" size={18} />錯誤事件</h2>{data.errors.length ? <div className="mt-4 space-y-3">{data.errors.map((row) => <div key={String(row.name)} className="flex justify-between rounded-xl bg-app-soft px-3 py-2 text-sm"><span className="text-main">{String(row.name)}</span><b className="text-coral-600">{num(row.count)}</b></div>)}</div> : <p className="mt-4 text-sm text-soft">此區間沒有 analytics error event。</p>}<p className="mt-4 text-xs text-soft">僅保存錯誤類型與必要統計，不保存密碼、Token、Cookie 或私人對話內容。</p></section></div>
    </>}
  </div>;
}
function Metric({ icon, label, value, compact }: { icon?: React.ReactNode; label: string; value: number; compact?: boolean }) { return <div className="card-surface rounded-2xl p-4"><p className="flex items-center gap-2 text-xs text-soft">{icon}{label}</p><p className={compact ? "mt-2 text-xl font-black text-main" : "mt-2 text-2xl font-black text-main"}>{value.toLocaleString()}</p></div>; }
function Ranking({ title, rows, nameKey, valueKey, secondKey, secondLabel }: { title: string; rows: Array<Record<string, string | number>>; nameKey: string; valueKey: string; secondKey: string; secondLabel: string }) { return <section className="card-surface rounded-3xl p-5"><h2 className="font-display text-lg font-black text-main">{title}</h2>{rows.length ? <div className="mt-4 space-y-2">{rows.slice(0, 10).map((row, index) => <div key={`${String(row[nameKey])}-${index}`} className="flex items-center justify-between gap-3 rounded-xl bg-app-soft px-3 py-2 text-sm"><span className="min-w-0 truncate text-main"><b className="mr-2 text-xs text-soft">{index + 1}</b>{String(row[nameKey])}</span><span className="shrink-0 text-right"><b className="text-main">{Number(row[valueKey] || 0).toLocaleString()}</b><small className="ml-2 text-xs text-soft">{secondLabel} {Number(row[secondKey] || 0).toLocaleString()}</small></span></div>)}</div> : <p className="mt-4 text-sm text-soft">尚無資料</p>}</section>; }
